## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.2
  - nightly

codecov: true

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    # - os: windows
    #   arch: x86
    #   julia: 1.0
    # - os: windows
    #   arch: x86
    #   julia: 1.2
    - os: windows
      arch: x86
      julia: nightly

#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran  # for Dierckx in the testing script
#before_script: # homebrew for mac
##  - if [ $TRAVIS_OS_NAME = osx ]; then brew cask uninstall oclint; fi  # https://github.com/travis-ci/travis-ci/issues/8826
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi  # for Dierckx in the testing script
